#!/usr/bin/env python3
"""A2L to OpenBSW framegateway XCP code generator.

Extracts CHARACTERISTIC (calibration) and MEASUREMENT (read-only) entries
from an ASAM MCD-2MC (A2L) file and generates code-first XcpSymbol tables
for the OpenBSW ``framegateway`` module.

Uses a small built-in parser for the common subset (no third-party
dependency); falls back gracefully on unknown constructs.

Outputs (into --output-dir):

- ``<prefix>XcpSymbols.cpp``  XcpSymbol initializer list
- ``<prefix>XcpSymbols.h``    extern declaration of the generated table
- ``<prefix>XcpSymbols.json`` JSON fragment for frame_gateway_config.json

Example:
    python tools/gateway/a2l_to_xcp.py ecu_calibration.a2l --output-dir src/config
"""

import argparse
import os
import re
import sys

A2L_TYPES = {
    "UBYTE": ("UINT8", 1),
    "SBYTE": ("INT8", 1),
    "UWORD": ("UINT16", 2),
    "SWORD": ("INT16", 2),
    "ULONG": ("UINT32", 4),
    "SLONG": ("INT32", 4),
    "FLOAT32_IEEE": ("FLOAT32", 4),
    "FLOAT64_IEEE": ("FLOAT64", 8),
}


class Symbol(object):
    def __init__(self, name, address, dtype, length, is_cal, unit):
        self.name = name
        self.address = address
        self.dtype = dtype
        self.length = length
        self.is_cal = is_cal
        self.unit = unit


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", text)


def parse_block(text, keyword):
    """Yield raw bodies of /begin KEYWORD ... /end KEYWORD blocks."""
    pattern = re.compile(r"/begin\s+" + keyword + r"\b(.*?)/end\s+" + keyword,
                         re.DOTALL | re.IGNORECASE)
    for match in pattern.finditer(text):
        yield match.group(1)


def parse_symbols(a2l_text):
    text = strip_comments(a2l_text)
    symbols = []
    for kind, is_cal in (("CHARACTERISTIC", True), ("MEASUREMENT", False)):
        for body in parse_block(text, kind):
            tokens = re.findall(r'"([^"]*)"|(\S+)', body)
            words = [a if a else b for a, b in tokens]
            if len(words) < 5:
                continue
            name = words[0]
            address = 0
            dtype = "ULONG"
            unit = ""
            addr_match = re.search(r"ECU_ADDRESS\s+(0x[0-9a-fA-F]+|\d+)", body,
                                   re.IGNORECASE)
            if addr_match:
                address = int(addr_match.group(1), 0)
            for word in words:
                if word.upper() in A2L_TYPES:
                    dtype = word.upper()
                    break
            unit_match = re.search(r"/begin\s+UNIT\b[^/]*?\"([^\"]*)\"",
                                   body, re.IGNORECASE | re.DOTALL)
            if unit_match:
                unit = unit_match.group(1)
            xcp_type, length = A2L_TYPES.get(dtype.upper(), ("UINT32", 4))
            symbols.append(Symbol(name, address, xcp_type, length, is_cal, unit))
    return symbols


def emit_header(symbols, prefix):
    lines = [
        "// Generated by a2l_to_xcp.py -- DO NOT EDIT.",
        "#pragma once",
        '#include "framegateway/XcpSymbolTable.h"',
        "#include <cstddef>",
        "",
        "extern framegateway::XcpSymbol const g_xcpSymbols[];",
        "extern size_t const g_xcpSymbolCount;",
        "",
    ]
    return "\n".join(lines)


def emit_source(symbols, prefix):
    lines = [
        "// Generated by a2l_to_xcp.py -- DO NOT EDIT.",
        '#include "%sXcpSymbols.h"' % prefix,
        "",
        "framegateway::XcpSymbol const g_xcpSymbols[] = {",
    ]
    for sym in symbols:
        cal = "true" if sym.is_cal else "false"
        lines.append(
            '    {"%s", 0x%XU, %dU, framegateway::XcpDataType::%s, %s, 0.0, 0.0, "%s"},'
            % (sym.name, sym.address, sym.length, sym.dtype, cal, sym.unit))
    lines += [
        "};",
        "",
        "size_t const g_xcpSymbolCount = "
        "sizeof(g_xcpSymbols) / sizeof(g_xcpSymbols[0]);",
        "",
    ]
    return "\n".join(lines)


def emit_json(symbols):
    import json
    entries = [
        {"name": s.name, "address": s.address, "length": s.length,
         "dataType": s.dtype, "isCalibration": s.is_cal,
         "min": 0, "max": 0, "unit": s.unit}
        for s in symbols
    ]
    return json.dumps({"xcpSymbols": entries}, indent=2) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description="A2L to OpenBSW XCP generator")
    parser.add_argument("a2l", help="input A2L file")
    parser.add_argument("--output-dir", default=".", help="output directory")
    parser.add_argument("--prefix", default="", help="output file prefix")
    args = parser.parse_args(argv)

    with open(args.a2l, "r", encoding="utf-8", errors="replace") as handle:
        symbols = parse_symbols(handle.read())

    os.makedirs(args.output_dir, exist_ok=True)
    with open(os.path.join(args.output_dir, args.prefix + "XcpSymbols.h"), "w",
              encoding="utf-8") as handle:
        handle.write(emit_header(symbols, args.prefix))
    with open(os.path.join(args.output_dir, args.prefix + "XcpSymbols.cpp"), "w",
              encoding="utf-8") as handle:
        handle.write(emit_source(symbols, args.prefix))
    with open(os.path.join(args.output_dir, args.prefix + "XcpSymbols.json"), "w",
              encoding="utf-8") as handle:
        handle.write(emit_json(symbols))

    print("symbols: %d -> %s" % (len(symbols), args.output_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
