/********************************************************************************
 * Copyright (c) 2026 Accenture
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

/**
 * \file
 * \ingroup canstack
 */
#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <string>
#include <utility>
#include <vector>

namespace canstack
{

/// DBC derived signal description.
struct SignalConfig
{
    std::string signalName;
    uint32_t frameId = 0U;
    uint8_t startBit = 0U;
    uint8_t length = 0U;
    /// true = Motorola / big endian bit numbering, false = Intel / little endian
    bool isMotorola = false;
    double factor = 1.0;
    double offset = 0.0;
    double min = 0.0;
    double max = 0.0;
    std::string unit;
    uint8_t channelId = 0U;
    /// true for the multiplexer selector signal of a multiplexed frame
    bool isMultiplexerSwitch = false;
    /// multiplexer switch value the signal belongs to; -1 = unconditional signal
    int16_t multiplexValue = -1;
    /// true for signed signals (DBC '@1-' / '@0-')
    bool isSigned = false;
};

/// DBC derived frame description.
struct FrameConfig
{
    uint32_t frameId = 0U;
    std::string frameName;
    uint8_t dlc = 0U;
    uint8_t channelId = 0U;
    std::vector<SignalConfig> signals;
};

/**
 * Code-first signal table entry (constexpr friendly).
 *
 * Generated by tools/can/dbc_to_openbsw.py or written by hand. The entries are
 * plain aggregates so they can live in constexpr tables; loadSignalTable()
 * copies them into the database.
 */
struct SignalTableEntry
{
    char const* signalName;
    uint32_t frameId;
    uint8_t startBit;
    uint8_t length;
    bool isMotorola;
    double factor;
    double offset;
    double min;
    double max;
    char const* unit;
    uint8_t channelId;
    bool isMultiplexerSwitch;
    int16_t multiplexValue;
    bool isSigned;
};

/// Code-first frame table entry (constexpr friendly).
struct FrameTableEntry
{
    uint32_t frameId;
    char const* frameName;
    uint8_t dlc;
    uint8_t channelId;
};

/// Maximum signal length in bits supported by pack/unpack.
static uint8_t const SIGNAL_MAX_BIT_LENGTH = 64U;

/**
 * Signal database holding the frame and signal layout of all channels.
 *
 * Two ways of filling the database:
 *
 * 1. Code-first: constexpr SignalTableEntry/FrameTableEntry arrays passed to
 *    loadFrameTable()/loadSignalTable(). The arrays are typically generated
 *    from a DBC file (see tools/can/dbc_to_openbsw.py) and compiled into the
 *    application.
 *
 * 2. Runtime: loadFromDbc() parses a DBC file directly (e.g. on POSIX systems
 *    where the file is available at runtime).
 */
class SignalDatabase
{
public:
    /**
     * Parses a DBC file and replaces the database content.
     * \param dbcFilePath path of the DBC file
     * \param channelId channel the frames belong to (DBC files carry no
     * channel information)
     * \return true when the file was parsed successfully
     */
    bool loadFromDbc(std::string const& dbcFilePath, uint8_t channelId = 0U);

    /// Replaces the frame table with code-first entries.
    void loadFrameTable(FrameTableEntry const* entries, size_t count);

    /// Adds/merges code-first signal entries into the frame table.
    void loadSignalTable(SignalTableEntry const* entries, size_t count);

    /// Removes all frames and signals.
    void clear();

    FrameConfig const* getFrameByChannelAndId(uint8_t channelId, uint32_t frameId) const;

    SignalConfig const* getSignalByName(std::string const& signalName) const;

    /**
     * Packs a physical value into the raw frame data.
     * The value is clamped to the configured signal range; the raw value is
     * computed as round((value - offset) / factor).
     */
    void packSignal(uint8_t* frameData, SignalConfig const& signal, double value) const;

    /// Unpacks a physical value from the raw frame data.
    double unpackSignal(uint8_t const* frameData, SignalConfig const& signal) const;

    size_t getFrameCount() const;
    size_t getSignalCount() const;

private:
    bool parseDbcLine(std::string const& line, uint8_t channelId);
    void storeFrame(FrameConfig const& frame);
    void storeSignal(SignalConfig const& signal);

    std::map<std::pair<uint8_t, uint32_t>, FrameConfig> m_frames;
    std::map<std::string, SignalConfig> m_signalsByName;
};

} // namespace canstack
